apiVersion: v1
kind: Service
metadata:
  name: springjasypt
  labels:
    app: springjasypt
  namespace: samples
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8088
  selector:
    app: springjasypt
  type: NodePort
