apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springjasypt
  namespace: samples
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springjasypt
        version: v1
    spec:
      containers:
      - name: springjasypt
        image: <containerrepourlforimage>
        env:
        - name: JAVA_OPTS
          value: -Xms128m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
        - name: MYSQL_DB_USER
          value: "ENC(1cWxyUbkZeqw+LYA/LyRhg==)"
        - name: MYSQL_DB_SERVER
          value: "<databasehostname or ip>"
        - name: MYSQL_DB_PASSWD
          value: "ENC(wUVs1lmbkgB7OqSPhKeFKVTY8siHCoag)"
        - name: JASYPT_ENCRYPTOR_ALGORITHM
          value: "PBEWithMD5AndDES"
        - name: JASYPT_ENCRYPTOR_PASSWORD
          value: "Password"
        ports:
        - containerPort: 8088
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
